name: Daily Update

on:
  schedule:
    - cron: '0 11,17,22 * * *'  # Runs at 11 AM, 5 PM, and 10 PM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run daily update script
        run: node dailyUpdate.js

      - name: Configure Git identity
        run: |
          git config --local user.name "Zakirhassan"
          git config --local user.email "zakirhassan114@gmail.com"

      - name: Push changes
        run: |
          git add .
          git commit -m "Daily update at $(date)"
          git push https://Zakirhassan:${{ secrets.PAT_TOKEN }}@github.com/Zakirhassan/Daily-Update.git
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
